import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { radarApi } from "../api/radar";
import { ChangeCard, EmptyState, ErrorState, EvidenceList, JsonData, LoadingState, StatusBadge } from "../components/ui";
import type { AgentAnswer, Change, CompetitorWorkspaceData, Insight, Snapshot } from "../types";

type Tab = "overview" | "data" | "changes" | "analyst";

export function CompetitorPage() {
  const rawId = useParams().id; const competitorId = Number(rawId);
  const [data, setData] = useState<CompetitorWorkspaceData>(); const [error, setError] = useState<string>(); const [tab, setTab] = useState<Tab>("overview"); const [collecting, setCollecting] = useState(false); const [collectError, setCollectError] = useState<string>();
  const load = async () => { setError(undefined); try { const competitor = await radarApi.getCompetitor(competitorId); const sources = await radarApi.listSources(competitorId); const [runs, snapshots, changes, insights] = await Promise.all([Promise.all(sources.map((source) => radarApi.listRuns(source.id))), Promise.all(sources.map((source) => radarApi.listSnapshots(source.id))), Promise.all(sources.map((source) => radarApi.listChanges(source.id))), radarApi.listInsights(competitorId)]); setData({ competitor, sources, runsBySource: Object.fromEntries(sources.map((source, i) => [source.id, runs[i]])), snapshotsBySource: Object.fromEntries(sources.map((source, i) => [source.id, snapshots[i]])), changesBySource: Object.fromEntries(sources.map((source, i) => [source.id, changes[i]])), insights }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load this competitor."); } };
  useEffect(() => { if (Number.isInteger(competitorId) && competitorId > 0) void load(); }, [competitorId]);
  const collect = async () => { if (!data) return; setCollecting(true); setCollectError(undefined); try { await Promise.all(data.sources.filter((source) => source.active && source.collector_id).map((source) => radarApi.collectSource(source.id))); await load(); } catch (caught) { setCollectError(caught instanceof Error ? caught.message : "Collection failed."); } finally { setCollecting(false); } };
  if (!Number.isInteger(competitorId) || competitorId < 1) return <ErrorState message="This competitor address is invalid." />;
  if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  if (!data) return <LoadingState label="Loading competitor workspace…" />;
  const latestRuns = Object.values(data.runsBySource).flat().sort((a, b) => new Date(b.finished_at ?? b.started_at).getTime() - new Date(a.finished_at ?? a.started_at).getTime()); const latestRun = latestRuns[0];
  return <>
    <Link className="back-link" to="/">← All competitors</Link>
    <header className="workspace-header"><div><div className="workspace-title"><span className="avatar large">{data.competitor.name.slice(0, 1).toUpperCase()}</span><div><p className="eyebrow">COMPETITOR WORKSPACE</p><h1>{data.competitor.name}</h1><a className="url" href={data.competitor.website_url} target="_blank" rel="noreferrer">{data.competitor.website_url.replace(/^https?:\/\//, "")} ↗</a></div></div></div><div className="workspace-actions">{latestRun && <StatusBadge value={latestRun.health_status} />}<button className="button primary" onClick={() => void collect()} disabled={collecting || !data.sources.some((source) => source.collector_id)}>{collecting ? "Collecting…" : "Collect latest data"}</button></div></header>
    {collectError && <p className="inline-error">{collectError}</p>}
    <nav className="tabs">{(["overview", "data", "changes", "analyst"] as Tab[]).map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item === "analyst" ? "AI Analyst" : item}</button>)}</nav>
    {tab === "overview" && <Overview data={data} latestRun={latestRun} onSelectTab={setTab} />}
    {tab === "data" && <DataTab data={data} />}
    {tab === "changes" && <ChangesTab data={data} onRefresh={load} />}
    {tab === "analyst" && <AnalystTab competitorId={competitorId} competitorName={data.competitor.name} />}
  </>;
}

function Overview({ data, latestRun, onSelectTab }: { data: CompetitorWorkspaceData; latestRun: CompetitorWorkspaceData["runsBySource"][number][number] | undefined; onSelectTab: (tab: Tab) => void }) {
  const latestSnapshots = Object.values(data.snapshotsBySource).map((snapshots) => snapshots[0]).filter(Boolean); const changes = Object.values(data.changesBySource).flat();
  return <div className="overview"><div className="metric-grid"><Metric label="Sources" value={String(data.sources.length)} detail={data.sources.length ? "Public pages monitored" : "No sources yet"} /><Metric label="Latest collection" value={latestRun?.finished_at ? new Date(latestRun.finished_at).toLocaleDateString() : "Not collected"} detail={latestRun ? `${latestRun.record_count} records returned` : "Run your first collection"} /><Metric label="Latest snapshots" value={String(latestSnapshots.length)} detail="Current source states" /><Metric label="Detected changes" value={String(changes.filter((change) => !["initial", "unchanged"].includes(change.change_type)).length)} detail="Verified changes" /></div>
    <div className="split-section"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">MONITOR STATUS</p><h2>Sources</h2></div><button className="button text" onClick={() => onSelectTab("data")}>View data →</button></div>{data.sources.length ? <div className="source-list">{data.sources.map((source) => { const run = data.runsBySource[source.id]?.[0]; return <div className="source-row" key={source.id}><div><strong>{source.name}</strong><a href={source.url} target="_blank" rel="noreferrer">{source.url}</a></div><div>{source.collector_id ? <StatusBadge value={run?.health_status ?? "ready"} /> : <StatusBadge value="setup needed" />}</div></div>; })}</div> : <EmptyState title="No sources configured" detail="Add a public source before collecting data." />}</section>
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">LATEST INTELLIGENCE</p><h2>AI insight</h2></div><button className="button text" onClick={() => onSelectTab("changes")}>View changes →</button></div>{data.insights[0] ? <InsightPreview insight={data.insights[0]} /> : <EmptyState title="No insight yet" detail="Analyze a verified change to generate an evidence-backed interpretation." />}</section></div></div>;
}
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="metric"><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>; }
function InsightPreview({ insight }: { insight: Insight }) { return <div className="insight-preview"><h3>{insight.title}</h3><p>{insight.analysis}</p><p><strong>Impact:</strong> {insight.competitive_impact}</p></div>; }

function DataTab({ data }: { data: CompetitorWorkspaceData }) { const records = data.sources.map((source) => ({ source, snapshot: data.snapshotsBySource[source.id]?.[0] })).filter((item): item is { source: CompetitorWorkspaceData["sources"][number]; snapshot: Snapshot } => Boolean(item.snapshot)); return <section className="panel full-panel"><div className="panel-heading"><div><p className="eyebrow">STRUCTURED DATA</p><h2>Latest collected data</h2></div></div>{records.length ? <div className="data-sources">{records.map(({ source, snapshot }) => <article className="data-source" key={source.id}><div className="data-source-heading"><div><h3>{source.name}</h3><a href={source.url} target="_blank" rel="noreferrer">{source.url} ↗</a></div><small>Captured {new Date(snapshot.captured_at).toLocaleString()}</small></div><JsonData value={snapshot.normalized_data} /></article>)}</div> : <EmptyState title="No snapshot available yet" detail="Run a collection to see the structured data Bright Data returned." />}</section>; }

function ChangesTab({ data, onRefresh }: { data: CompetitorWorkspaceData; onRefresh: () => Promise<void> }) { const [analyzingId, setAnalyzingId] = useState<number>(); const [error, setError] = useState<string>(); const changes = useMemo(() => Object.values(data.changesBySource).flat().sort((a, b) => b.id - a.id), [data]); const insightByChange = new Map(data.insights.filter((insight) => insight.change_id !== null).map((insight) => [insight.change_id, insight])); const analyze = async (id: number) => { setAnalyzingId(id); setError(undefined); try { await radarApi.analyzeChange(id); await onRefresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not generate the insight."); } finally { setAnalyzingId(undefined); } }; return <section className="changes"><div className="section-header"><div><p className="eyebrow">VERIFIED ACTIVITY</p><h2>Changes</h2></div></div>{error && <p className="inline-error">{error}</p>}{changes.length ? <div className="change-list">{changes.map((change) => <ChangeCard key={change.id} change={change} insight={insightByChange.get(change.id)} onAnalyze={() => void analyze(change.id)} analyzing={analyzingId === change.id} />)}</div> : <EmptyState title="No meaningful changes detected yet" detail="After a second collection, this view will show deterministic changes to the source data." />}</section>; }

type Message = { role: "user" | "assistant"; content: string; evidence?: AgentAnswer["evidence"] };
function AnalystTab({ competitorId, competitorName }: { competitorId: number; competitorName: string }) { const [messages, setMessages] = useState<Message[]>([]); const [question, setQuestion] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string>(); const ask = async (value = question) => { const trimmed = value.trim(); if (!trimmed || loading) return; setMessages((current) => [...current, { role: "user", content: trimmed }]); setQuestion(""); setLoading(true); setError(undefined); try { const answer = await radarApi.askCompetitor(competitorId, trimmed); setMessages((current) => [...current, { role: "assistant", content: answer.answer, evidence: answer.evidence }]); } catch (caught) { setError(caught instanceof Error ? caught.message : "The AI Analyst could not answer right now."); } finally { setLoading(false); } }; const starters = ["What products do they currently offer?", "What are their current prices?", "Which product is the most expensive?", "What changed recently?"]; return <section className="analyst"><div className="analyst-intro"><p className="eyebrow">AI ANALYST · {competitorName.toUpperCase()}</p><h2>Ask about their collected data.</h2><p>Answers are based only on your latest collected competitor data and verified changes.</p></div><div className="chat-panel">{messages.length === 0 ? <div className="chat-empty"><p>Start with a question</p><div className="starter-list">{starters.map((starter) => <button key={starter} onClick={() => void ask(starter)} disabled={loading}>{starter} →</button>)}</div></div> : <div className="messages">{messages.map((message, index) => <article className={`message ${message.role}`} key={index}><p className="message-label">{message.role === "user" ? "YOU" : "AI ANALYST"}</p><p>{message.content}</p>{message.evidence && <EvidenceList evidence={message.evidence} />}</article>)}{loading && <div className="thinking"><span className="spinner" />AI Analyst is analyzing the latest competitor data…</div>}</div>} {error && <p className="inline-error">{error}</p>}<form className="chat-input" onSubmit={(event) => { event.preventDefault(); void ask(); }}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder={`Ask about ${competitorName}…`} disabled={loading} /><button className="button primary" type="submit" disabled={loading || !question.trim()}>Ask ↑</button></form></div></section>; }
